version: '3.8'

services:
  db-mariadb:
    image: mariadb:11.2
    container_name: db-mariadb
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - data:/var/lib/mysql
    ports:
      - "5432:5432"
    networks: 
        - api-network

  web:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - db-mariadb
    volumes:
      - .:/app
    networks: 
        - api-network

volumes:
  data:

networks:
  api-network:
    driver: bridge